### ISSUE TITLE
Typo in Admin Hook #5 System Post Filter

### ISSUE THREAD

**Issue by kartguru** [aurovrata/Post-My-CF7-Form#13]
Hi

  displayed_posts['some_post'] = 'Some Post';
  return displayed_posts;

to read

  $displayed_posts['some_post'] = 'Some Post';
  return $displayed_posts;

**Comment by aurovrata** [comment]
thanks!  Yes, the $ would be good to have there.

You know you can fork this repo, fix the typo in your copy and then submit a PR which I just merge back into the code :smiley:

**Comment by kartguru** [comment]
@aurovrata , I'm an amateur but I will have a go at your instructions. I have tried a PR in the past but it failed, I think it was due to permissions. No fork was created in the process though. Cheers

**Comment by aurovrata** [comment]
Have you tried a [video tutorial](https://www.youtube.com/watch?v=rgbCcBNZcdQ) to understand how to?

>  I think it was due to permissions

indeed, you can fork the repo into your own account (you make a copy of the files).  You can then make the changes in that copy.  However, when you submit the changed code as a PR, only the original author of the code (me) has permission to merge the PR back into the original code :)

Please fork the [current version](https://github.com/aurovrata/post-my-cf7-form/tree/master).  The default is now on v5 which is being coded for the next major release.
