### ISSUE TITLE
search.png css background image url error

### ISSUE THREAD

**Issue by KurdishDB** [aurovrata/Post-My-CF7-Form#16]
So you have:

### _**cf7-grid-layout/public/css/cf7-grid-layout-public.css**_

(Line 252) background-image: url('search.png'); 

You also have:

### _cf7-grid-layout/public/css/**min**/cf7-grid-layout-public.css_

.cf7-smart-grid.has-grid input.select2-search__field{background-image:url(search.png);

Problem is there is no search.png in min directory so image fails to load.

**Comment by aurovrata** [comment]
well spotted...however wrong plugin repo.  this is the Post My CF7 plugin, but the bug is in the [CF7 Smart Grid extension](https://github.com/aurovrata/cf7-grid-layout).

**Comment by aurovrata** [comment]
Fixed in v4.7.9 of the smart grid.
