### ISSUE TITLE
Would it be possible to add a filter to change this value?

### ISSUE THREAD

**Issue by riccardodicurti** [aurovrata/Post-My-CF7-Form#18]
Hi, it would be very convenient for me that the posts created were not drafts, it would be possible to create a filter to change this value.

https://github.com/aurovrata/post-my-cf7-form/blob/2d2b9bd69b783f18d0132c8f789aa7923e056a9e/includes/mapper/class-cf7-2-post-mapper.php#L773

**Comment by aurovrata** [comment]
there is already a mechanism to change the status of a post, please read the FAQ in the plugin page.
