### ISSUE TITLE
(pre-releases V5.5 & V4.15) Deactivating Contactform7 locks out administrator

### ISSUE THREAD

**Issue by anton-vrba** [aurovrata/Post-My-CF7-Form#22]
I installed the prereleases V5.5 and V4.15, I then wanted to update Contactform7 to the latest release, and deactivated the installed version.

Now I get the message  "CF7 smart Grid-layout Extension requires Contact Form 7 plugin, and has therefore been deactivated!" when in wp_admin, but plugins were not deactivated, thus locked out from admin functions

Had to go to cPanel and renamed the directories of Grid-Layout and Post My CF7 Form (forcing a deactivation) to regain admin access.

**Comment by aurovrata** [comment]
Bummer, will look into this to see how to get a cleaner exit

**Comment by anton-vrba** [comment]
Curiosity killed the cat!  I had a look at your code.

And checking `deactivate_plugins`  https://developer.wordpress.org/reference/functions/deactivate_plugins/  we see deactivation is by a `do_action`.  Now the `wp_die` stops that deactivation action from happening. 

The fix is simple, introduce a `sleep()`  it worked for me:
**CF7 Smart Grid Design Extension** 
```
 public function check_plugin_dependency() {
    //if either the polylang for the cf7 plugin is not active anymore, deactive this extension
    if( !is_plugin_active("contact-form-7/wp-contact-form-7.php") ){
        deactivate_plugins( "cf7-grid-layout/cf7-grid-layout.php" );

        sleep(1) ;  //  now let WP do its thing to deactivate the pluging 

        debug_msg("Deactivating Smart Grid");
        $button = '<a href="'.network_admin_url('plugins.php').'">Return to Plugins</a></a>';
        wp_die( '<p><strong>CF7 smart Grid-layout Extension</strong> requires <strong>Contact Form 7</strong> plugin, and has therefore been deactivated!</p>'.$button );

        return false;
    }
    return true;
  }
```

and **Post My CF7 Form** also adding the return to plugin link like above
```
  public function check_plugin_dependency() {
    if( !is_plugin_active('contact-form-7/wp-contact-form-7.php') ){
      deactivate_plugins( "post-my-contact-form-7/cf7-2-post.php" );
      sleep(1) ;
      debug_msg("Deactivating Post My CF7 Form");

        $button = '<a href="'.network_admin_url('plugins.php').'">Return to Plugins</a></a>';
        wp_die( '<p><strong>Post My CF7 Form</strong> requires <strong>Contact Form 7</strong> plugin, and has therefore been deactivated!</p>'.$button );
//      wp_die( __('<strong>Post My CF7 Form</strong> requires <strong>CF7 plugin</strong> and has been deactivated!','post-my-contact-form-7') );
    }
		/** @since 5.0.0 hook the smart grid form saving action to fix double save_post hook call*/
    if(is_plugin_active('cf7-grid-layout/cf7-grid-layout.php')){
			add_action('cf7sg_save_post', array($this, 'save_post_mapping'), 10);
    }else{
			add_action('save_post_wpcf7_contact_form', array($this, 'save_post_mapping'), 10);
		}
  }
```

**Comment by aurovrata** [comment]
ya, actually the problem is that you installed the beta version 5.5 which has the wrong slug (post-my-cf7-form instead of post-my-contact-form-7) and hence it never gets deactivated, resulting in an infinite loop with wp_die.

I just renamed the github repo to refelct the wp repo name, so this situation does not arise in the future :slightly_smiling_face:
