### ISSUE TITLE
taxonomy hook with a filter

### ISSUE THREAD

**Issue by netzgestaltung** [aurovrata/Post-My-CF7-Form#8]
in [/includes/class-cf7-2-post-factory.php on line 1442](https://github.com/aurovrata/Post-My-CF7-Form/blob/80a9212e29803a00b8f15fdc720d24199e7837c7/includes/class-cf7-2-post-factory.php#L1442) the true condition leads to adding an empty array instead of a filter function.

```javascript
if( 0 === strpos($form_field,'cf7_2_post_filter-') ) {
  $value = apply_filters($form_field, array(), $post_id, $cf7_form_data);
}
```
i think there should be `'cf7_2_post_filter-' . $this->post_properties['type'] . '-' . $field_to_map` instead of that empty array. Also the usage of ` $this->post_properties['type']` seems unconsistent sometimes with and somethimes without.

**Comment by netzgestaltung** [comment]
i will inspect my issue more after reading some docs

**Comment by aurovrata** [comment]
>i think there should be 'cf7_2_post_filter-' . $this->post_properties['type'] . '-' . $field_to_map

this is to identiy the field in the form?  When I created the plugin, I wasn't very consistent in my creation of filters.  I would change this filter to:

`$value = apply_filters($form_field, array(), $post_id, $cf7_form_data, $cf7_key);`

which would allow a user to identify the form being submitted.

> Also the usage of $this->post_properties['type'] seems unconsistent sometimes with and somethimes without.

yes, that's quite possible, and hopefully can be improved in v5

**Comment by netzgestaltung** [comment]
please refer to https://github.com/aurovrata/post-my-cf7-form/pull/9 where i figured it all out.

i think a filter should not only get an empty array but instead the possible estimated value instead

**Comment by aurovrata** [comment]
> i think a filter should not only get an empty array 

Well, if multiple functions are hooked then you want the same value type to be passed, in this case an array.

> instead the possible estimated value instead

in this case there is no estimated value, since the user opts for the filtered option (ie no form fields mapped here).

**Comment by aurovrata** [comment]
I am going through the code and creating a [Wiki Page](https://github.com/aurovrata/post-my-cf7-form/wiki/Developers) on key functionality in processes handled by the plugin.
